### ISSUE TITLE
Feature: I want to make a BMI calculator

### ISSUE THREAD

**Issue by lrnzdc3696** [keshavsingh3197/hacktoberfest#1862]
### Is your feature request related to a problem? 
Please describe.
I have not seen a BMI calculator in python folder yet

### Describe the solution you'd like

make one and add it

### Describe alternatives you've considered

I will make it

### Additional context

It's just a cli

**Comment by ghost** [comment]
can i work on this issue please assing me if possible

**Comment by lrnzdc3696** [comment]
guys just make your own idea
don't take someone else's idea and make it.

**Comment by ghost** [comment]
> 
> 
> guys just make your own idea don't take someone else's idea and make it.

can i you please assing me this issue

**Comment by lrnzdc3696** [comment]
https://github.com/keshavsingh4522/hacktoberfest2021/pull/2969
