### ISSUE TITLE
Feature: Add quick sort in C 

### ISSUE THREAD

**Issue by DishantIsrani** [keshavsingh3197/hacktoberfest#2325]
I would love to implement the solution of quick sort in C

**Comment by svareed** [comment]
Please assign me this issue

**Comment by vivekarora-02** [comment]
Hey there,
Can you please assign me this issue?

ThankYou!

**Comment by mukul-web** [comment]
I would like to work on this issue.. Please assign me this !

**Comment by shubhamshah14102** [comment]
Hey ,
Would like to implement the the quick sort in c .
please assign this issue to me

**Comment by Khushi-Mattu** [comment]
Hey, i would like to work on this issue. please assign it to me!

**Comment by sonal019** [comment]
Please assign me this issue

**Comment by nishantpathak27** [comment]
I want to contribute in this. Please assign this to me

**Comment by Bhojraj-Kumar** [comment]
May i contribute!!

**Comment by Shubh8434** [comment]
plz assign it to me?

**Comment by bunish** [comment]
Hey, I can help resolve this issue. Please assign it to me.

**Comment by alpha-photon** [comment]
Hey, I can help to resolve this issue . Please assign this to me.

**Comment by himanshuv242** [comment]
Please assign me this issue sir i'm a beginner and want to start.

**Comment by sonal019** [comment]
[Quick sort using C.txt](https://github.com/keshavsingh4522/hacktoberfest2021/files/7360389/Quick.sort.using.C.txt)

**Comment by DurveshKumarPal** [comment]
@keshavsingh4522  @Dishant Israni   Check My PR #2894
