### ISSUE TITLE
Feature: Java Version of BMI Calcu 

### ISSUE THREAD

**Issue by lrnzdc3696** [keshavsingh3197/hacktoberfest#2423]
### Is your feature request related to a problem? Please describe.
BMI calculator but in Java

### Describe the solution you'd like
I will make it 

### Describe alternatives you've considered
nothing

### Additional context
it is the direct language traslation of my bmi calculator that I will be pull requesting

**Comment by bunish** [comment]
Hey, I can help resolve this issue. Please assign it to me.

**Comment by Thuvan96** [comment]
Please assign me to this issue
