### ISSUE TITLE
Selection Sort Algorithm

### ISSUE THREAD

**Issue by qasim0014** [keshavsingh3197/hacktoberfest#2532]
### Is your feature request related to a problem? Please describe.

Yes, I want to implement Selection sort algorithm in Java

### Describe the solution you'd like

I will make all the necessary CRUD operation methods

### Describe alternatives you've considered

Nope, since it is specific algorithm

### Additional context

Will add comments in all methods

**Comment by prehans** [comment]
Yes, I want to implement Selection sort algorithm in cpp.
@qasim0014

**Comment by Shubh8434** [comment]
I add not only selection sort but all the sorting algorithm in one program plz assign it to me @qasim0014 ?

**Comment by ishita3513** [comment]
I am happy to get the opportunity to contribute to this issue of selection sort  @qasim0014.

**Comment by vaishnavisaindane** [comment]
I want to contribute to this issue of selection sort in java @qasim0014 .Can you please assign it to me?

**Comment by Priya7781** [comment]
I want to contribute to this issue. Can u assign it to me @keshavsingh4522

**Comment by Anuja1510** [comment]
I would like to work on this issue under Hacktoberfest2021. I can implement the selection sort algorithm in CPP. Please assign it to me.

**Comment by Ankur7-7** [comment]
Hey @qasim0014, I want to contribute in this issue. kindly assign me this issue.
Thank You.

**Comment by real-phoenix** [comment]
Hello @qasim0014  and @keshavsingh4522  I would like to work on this issue under Hacktoberfest2021, I can implement the selection sort algorithm in CPP as I am  fluent with C++ ,  Data Structures and Algorithms , Please assign this to me. 
Thanks in Advance.

**Comment by AnujaDixit12** [comment]
Hello sir, can you please assign me this issue . I would like to contribute.

**Comment by qasim0014** [comment]
Closed
