### ISSUE TITLE
Feature: Calculator to compute volume of common 3D shapes in C

### ISSUE THREAD

**Issue by ShiviDev** [keshavsingh3197/hacktoberfest#2594]
### Is your feature request related to a problem? Please describe.

Calculator to compute volume of common 3D shapes in C.
This will be particularly useful to students who have to compute volumes since this abstracts and simplifies the whole process. 

### Describe the solution you'd like

User picks the shape of choice and inputs relevant dimensions. Volume will be returned.

### Additional context

Program will compute volume of the following shapes : 

- Cuboid
- Cylinder
- Prism
- Sphere
- Pyramid
- Right Circular Cone
- Tetrahedron

**Comment by ShiviDev** [comment]
Can I work on this?

**Comment by real-phoenix** [comment]
Hello @ShiviDev  and @keshavsingh4522  , I am student of IIT Roorkee Uttarakhand India , I have a strong background in Maths and Programming. 

I can easily calculate the Volume of figures Cuboid , Cylinder , Prism , Sphere , Square or Rectangular Pyramid , Right Circular Cone , Tetrahedron , Ellipsoid. 

Kindly  assign me this work.
