### ISSUE TITLE
Feature: C program to simulate unit conversion calculator

### ISSUE THREAD

**Issue by ShiviDev** [keshavsingh3197/hacktoberfest#2595]
### Is your feature request related to a problem? Please describe.

Unit conversion is a very common problem and this program aims to solve it by providing a variety of conversion options across different quantities.

### Describe the solution you'd like

A calculator C program that allows the user to convert between units of choice in the required physical quantity (mass, length etc)

### Additional context
The following physical quantities will have options for conversions :

- Length
- Temperature
- Area
- Volume
- Weight
- Time

**Comment by ShiviDev** [comment]
Can I work on this?

**Comment by AdamyJain** [comment]
I would like to work on this. Please assign this to me.
Thank you

**Comment by FieldMarshallObvious** [comment]
If it's still possible, could I get assigned to this?
