### ISSUE TITLE
Feature: create an odd or even program

### ISSUE THREAD

**Issue by srinivasthedeveloper** [keshavsingh3197/hacktoberfest#2890]
in your fav language try to make the most stupid odd or even program

**Comment by DurveshKumarPal** [comment]
@srinivasthedeveloper can you assign me under HacktoberFest2021

**Comment by anshshankar** [comment]
@srinivasthedeveloper please assign me

**Comment by rahultg1411** [comment]
@srinivasthedeveloper please assign this to me

**Comment by bhumithakur** [comment]
@srinivasthedeveloper please assign this to me i'll code this in different way

**Comment by akarshlahariya11** [comment]
@srinivasthedeveloper please assign me this issue.

**Comment by Tharunkumar1411** [comment]
can you assign this issue for me?

**Comment by LazyMagician** [comment]
Please assign me this issue as my first contribution to hactoberfest 2021 @srinivasthedeveloper

**Comment by soumyo2002** [comment]
Dear @srinivasthedeveloper sir, Please assign me this task and I shall finish it in no time. It will be really helpful as it will become my first contribution. Thank you

**Comment by ishita1505** [comment]
@srinivasthedeveloper sir, please assign this task to me . It will be very helpful. Thankyou.

**Comment by real-phoenix** [comment]
Hello @srinivasthedeveloper  and @keshavsingh4522 I would like to work on this issue under Hacktoberfest2021, I can implement the selection sort algorithm in CPP as I am fluent with C++ , Data Structures and Algorithms , Please assign this to me.
Thanks in Advance.

**Comment by shreykpatnaik** [comment]
Please assign this to me. I would like to work upon this as my first contribution for this season.

**Comment by AsmaIbrahimButt** [comment]
@srinivasthedeveloper KIndly assign to me.I will do this in a different way that will be helpful for others too.thanku

**Comment by Loveena28** [comment]
@srinivasthedeveloper I would like to work on this issue. Please assign me this one.
