### ISSUE TITLE
Binary Tree missing in DSA.

### ISSUE THREAD

**Issue by tusharjha44** [keshavsingh3197/hacktoberfest#3623]

**Comment by tusharjha44** [comment]
@keshavsingh4522 as this repo does not contain any information on one of the DSA topic Binary Tree. I would like to add some some traversals and build tree from that traversals method.

Please assign this issue to me

**Comment by Sumercode** [comment]
Please assign this task to me

**Comment by Ishantgarg-web** [comment]
please assign this task to me

**Comment by Ayushisri29** [comment]
please assign this to me i would like to work on it

**Comment by Himanshi2511** [comment]
@tusharjha44 please assign this task to me

**Comment by coder-dash23** [comment]
I want to add binary tree in binary tree in DSA please assign this issue to me

**Comment by theshreyaa** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if I can get some more info to work with

**Comment by Jayant-001** [comment]
Hello, I am interested to work on  this issue.
Could you please assign it to me.

**Comment by mayank-9** [comment]
Hey ! I would love to work on this ,
Could you please assign it to me.

**Comment by Aniketmishra0** [comment]
Can you assign me

**Comment by AnujaDixit12** [comment]
Hello sir, can you please assign me this issue . I would like to contribute.

**Comment by sp-gits** [comment]
**can you assign this issue to me ?**

**Comment by prabhat108** [comment]
HEY PLEASE ASSIGN IT TO ME

**Comment by kalkeshwar** [comment]
Found error: No binary Trees concepts in Dsa only AVL Trees are available
Expected Behaviour: Adding Folder of binary trees and adding the solutions like inorder traversal, preorder traversal, post order traversal, level wise traversing ,and some solutions for problems like invert binary tree,validate binary tree, etc.....

Iam interested to add those files if any extra resources you want to add then let us discuss here. .

can you assign this issue to me?

**Comment by kalkeshwar** [comment]
@keshavsingh4522  I made a pull request which add these feature.please make sure to see the request and update any things.

**Comment by kalkeshwar** [comment]
Hi, @keshavsingh4522 , please review and accept the pull request #4523 which solves these issue.
