### ISSUE TITLE
Feature: Finding parent of a node from post-order traversal

### ISSUE THREAD

**Issue by nikita24383** [keshavsingh3197/hacktoberfest#3895]
## Finding parent of a node from post-order traversal

Given the height of tree finding the parent of a particular node from post order traversal.
I'd like to add this code in python.

**Comment by adityjoshi** [comment]
hey @nikita24383 can I contribute to this issue

**Comment by nikita24383** [comment]
hello! @adityjoshi i apologize but I'd like to work on this issue
