### ISSUE TITLE
Feature:  STL

### ISSUE THREAD

**Issue by narwar-veer** [keshavsingh3197/hacktoberfest#3916]
### Is your feature request related to a problem? Please describe.

STL is difficult to understand and use to newbies.

### Describe the solution you'd like

I will contribute a simple documentation along with simple codes

**Comment by narwar-veer** [comment]
I am waiting for your permission.

**Comment by itsrishav17** [comment]
I want to contribute to this project can you please assign me?

**Comment by Aryaman047** [comment]
I want to contribute to this project and would like to contribute by providing a detailed documentation, possibly video explanations and provide sample codes if it's about teaching.

If STL has to be implemented in a program, I am confident to provide an accurate solution
